import os
import shutil


# =============================================================================
def gmx_minim_template(gmxpath, topologyfile, nsteps_min=1000):

    lines = ';----------------------------------------------------------------------------------------------------\n'
    lines += '; Author      : Javier Ramos\n'
    lines += '; Last Edited : 12.02.2024\n'
    lines += ';---------------------------------------------------------------------------------------------------\n'
    lines += '\n'
    lines += '\n'
    lines += '; RUN CONTROL PARAMETERS\n'
    lines += '; --------------------------------------------------------------------------------------------------\n'
    lines += 'integrator               = steep   ; for equilibriation this is good\n'
    lines += 'tinit                    = 0       ; default\n'
    lines += 'dt                       = 0.002   ; [1]\n'
    lines += 'nsteps                   = {}  ; 8 ns of sampleing time\n'.format(nsteps_min)
    lines += 'init-step                = 0       ; default\n'
    lines += 'simulation-part          = 1       ; default\n'
    lines += 'comm-mode                = Linear  ; default\n'
    lines += 'nstcomm                  = 100     ; [1]\n'
    lines += 'comm-grps                = system  ; [1]\n'
    lines += '\n'
    lines += '; OUTPUT CONTROL OPTIONS\n'
    lines += '; --------------------------------------------------------------------------------------------------\n'
    lines += 'nstxout                  = 100\n'
    lines += 'nstvout                  = 0\n'
    lines += 'nstfout                  = 0\n'
    lines += 'nstlog                   = 0\n'
    lines += 'nstcalcenergy            = 100\n'
    lines += 'nstenergy                = 100\n'
    lines += 'nstxout-compressed       = 1\n'
    lines += 'compressed-x-precision   = 0\n'
    lines += 'compressed-x-grps        = \n'
    lines += 'energygrps               = \n'
    lines += '\n'
    lines += '\n'
    lines += '; NEIGHBORSEARCHING PARAMETERS\n'
    lines += '; ---------------------------------------------------------------------------------------\n'
    lines += 'cutoff-scheme            = verlet  ; should be faster at same accuracy\n'
    lines += 'nstlist                  = 20      ; [1]\n'
    lines += 'ns_type                  = grid    ; default\n'
    lines += 'pbc                      = xyz     ; [1]\n'
    lines += 'periodic-molecules       = no\n'
    lines += 'verlet-buffer-tolerance  = 1e-6    ; non-default but should improve accuracy\n'
    lines += 'rlist                    = 1.1     ; default\n'
    lines += '\n'
    lines += '\n'
    lines += '; OPTIONS FOR ELECTROSTATICS AND VDW\n'
    lines += '; -----------------------------------------------------------------------------------------\n'
    lines += 'coulombtype              = Reaction-field         ; [1]\n'
    lines += 'coulomb-modifier         = Potential-shift-Verlet ; ??? \n'
    lines += 'rcoulomb-switch          = 0\n'
    lines += 'rcoulomb                 = 1.2                    ; [1]\n'
    lines += 'epsilon-r                = 1                      ; relative eps. for the medium -> \n'
    lines += 'epsilon-rf               = 1.2                   ; [1]\n'
    lines += 'vdw-type                 = cut-off\n'
    lines += 'vdw-modifier             = Potential-shift-Verlet\n'
    lines += 'rvdw-switch              = 0\n'
    lines += 'rvdw                     = 1.2                    ; [1]\n'
    lines += 'DispCorr                 = no \n'
    lines += 'table-extension          = 1\n'
    lines += 'energygrp-table          = \n'
    lines += 'fourierspacing           = 0.1\n'
    lines += 'fourier-nx               = 0\n'
    lines += 'fourier-ny               = 0\n'
    lines += 'fourier-nz               = 0\n'
    lines += 'pme_order                = 4\n'
    lines += 'ewald_rtol               = 1e-05\n'
    lines += 'ewald_rtol_lj            = 1e-03\n'
    lines += 'lj-pme-comb-rule         = geometric\n'
    lines += 'ewald_geometry           = 3d\n'
    lines += 'epsilon_surface          = 0\n'
    lines += '\n'
    lines += '\n'
    lines += '; OPTIONS FOR WEAK COUPLING ALGORITHMS\n'
    lines += '; -----------------------------------------------------------------------------------------\n'
    lines += 'tcoupl                   = Berendsen            ; We equilibriate so this is good enough\n'
    lines += 'nsttcouple               = 5                    ; default\n'
    lines += 'nh-chain-length          = 10                   ; N/A\n'
    lines += 'print-nose-hoover-chain-variables = no          ; N/A\n'
    lines += 'tc-grps                  = system               ; For small molecules OK\n'
    lines += 'tau-t                    = 2                    ; default\n'
    lines += 'ref-t                    = 298.15               ; standard condition\n'
    lines += 'pcoupl                   = Berendsen               \n'
    lines += 'pcoupltype               = isotropic            ; We equilibriate so this is good enough\n'
    lines += 'nstpcouple               = 10\n'
    lines += 'tau-p                    = 1\n'
    lines += 'compressibility          = 9.62e-5              ; [1]\n'
    lines += 'ref-p                    = 1\n'
    lines += 'refcoord-scaling         = No\n'
    lines += '\n'
    lines += '; GENERATE VELOCITIES FOR STARTUP RUN\n'
    lines += '; -----------------------------------------------------------------------------------------\n'
    lines += 'gen-vel                  = yes        ; for free energy stuff we dont want this\n'
    lines += 'gen-temp                 = 298.15     ; N/A\n'
    lines += 'gen-seed                 = -1         ; N/A\n'
    lines += '\n'
    lines += '; OPTIONS FOR BONDS    \n'
    lines += '; -----------------------------------------------------------------------------------------\n'
    lines += 'constraints              = None  ; [1] water is done via shake\n'
    lines += '; Type of constraint algorithm\n'
    lines += 'constraint-algorithm     = Lincs      ; default\n'
    lines += 'continuation             = no         ; default\n'
    lines += 'Shake-SOR                = no         ; default\n'
    lines += 'shake-tol                = 0.0001     ; default also same as in [1]\n'
    lines += 'lincs-order              = 4          ; default\n'
    lines += 'lincs-iter               = 1          ; default\n'
    lines += 'lincs-warnangle          = 90         ; default\n'
    lines += 'morse                    = no         ; default\n'
    lines += '\n'
    lines += '; Free energy variables\n'
    lines += ';------------------------------------------------------------------------------------------\n'
    lines += 'free-energy              = no  ; only for equilibriation\n'

    with open("minim.mdp", "w") as fmin:
        fmin.writelines(lines)

    lines = '#!/bin/bash\n'
    lines += '#SBATCH --partition=#PARTITION#\n'
    lines += '#SBATCH -n #NPROCESORS#\n'
    lines += '#SBATCH -N 1\n'
    lines += '#SBATCH --mem-per-cpu=3G\n'
    name = os.path.splitext(os.path.split(topologyfile)[-1])[0]
    lines += '#SBATCH --job-name=#JOBNAME#\n'
    lines += '\n'
    lines += '#module purge\n'
    lines += '#module load foss GROMACS/2021.5\n'
    lines += '#source {}/GMXRC.bash\n'.format(os.path.split(gmxpath)[0])
    lines += 'source #GMXRCPATH#\n'
    lines += '\n'
    lines += '\n'
    lines += 'MDP="{}"\n'.format("minim.mdp")
    lines += 'GRO="{}"\n'.format("../coords.gro")
    lines += 'TOP="{}"\n'.format(os.path.join("../00-FORCE_FIELD_POLYPLY", topologyfile))
    lines += '\n'
    lines += 'gmx grompp -f $MDP -p $TOP -c $GRO -o new_topo.tpr --maxwarn 5 >& outgro.dat\n'
    lines += 'gmx mdrun  -nt 14 -s new_topo.tpr -v -noappend  >& outmd.dat\n'
    lines += '#gmx mdrun -s new_topo.tpr -v -noappend  >& outmd.dat\n'
    lines += '#echo 0|gmx trjconv -f traj_comp.part0001.xtc -o traj_unwrap.xtc -pbc whole -s new_topo.tpr'
    lines += '#echo 0|gmx trjconv -f confout.gro -o confout_unwrap.gro -pbc whole -s new_topo.tpr'
    lines += '\n'
    lines += r'rm \#*\n'
    lines += '\n'
    lines += '\n'

    with open("./sendslurm_min_cpu.sh", "w") as fnpt:
        fnpt.writelines(lines)


# ===============================================================================================
def gmx_eq1_nvt_template(gmxpath, topologyfile, md_steps=100000, dt=0.001):

    lines = ';----------------------------------------------------------------------------------------------------\n'
    lines += '; Author      : Javier Ramos\n'
    lines += '; Last Edited : 12.02.2024\n'
    lines += ';---------------------------------------------------------------------------------------------------\n'
    lines += '\n'
    lines += '\n'
    lines += '; RUN CONTROL PARAMETERS\n'
    lines += '; --------------------------------------------------------------------------------------------------\n'
    lines += 'integrator               = md      ; for equilibriation this is good\n'
    lines += 'tinit                    = 0       ; default\n'
    lines += 'dt                       = {0:7.3f} ; [1]\n'.format(dt)
    lines += 'nsteps                   = {0:10d} ; {1:7.1f}ps NVT Sampling time\n'.format(md_steps, md_steps*dt)
    lines += 'init-step                = 0       ; default\n'
    lines += 'simulation-part          = 1       ; default\n'
    lines += 'comm-mode                = Linear  ; default\n'
    lines += 'nstcomm                  = 100     ; [1]\n'
    lines += 'comm-grps                = system  ; [1]\n'
    lines += '\n'
    lines += '; OUTPUT CONTROL OPTIONS\n'
    lines += '; --------------------------------------------------------------------------------------------------\n'
    lines += 'nstxout                  = 0\n'
    lines += 'nstvout                  = 0\n'
    lines += 'nstfout                  = 0\n'
    lines += 'nstlog                   = 10000\n'
    lines += 'nstcalcenergy            = 10000\n'
    lines += 'nstenergy                = 10000\n'
    lines += 'nstxout-compressed       = 10000\n'
    lines += 'compressed-x-precision   = 1000\n'
    lines += 'compressed-x-grps        = \n'
    lines += 'energygrps               = \n'
    lines += '\n'
    lines += '\n'
    lines += '; NEIGHBORSEARCHING PARAMETERS\n'
    lines += '; ---------------------------------------------------------------------------------------\n'
    lines += 'cutoff-scheme            = verlet  ; should be faster at same accuracy\n'
    lines += 'nstlist                  = 40      ; [1]\n'
    lines += 'ns_type                  = grid    ; default\n'
    lines += 'pbc                      = xyz     ; [1]\n'
    lines += 'periodic-molecules       = no\n'
    lines += 'verlet-buffer-tolerance  = 1e-6    ; non-default but should improve accuracy\n'
    lines += 'rlist                    = 1.1     ; default\n'
    lines += '\n'
    lines += '\n'
    lines += '; OPTIONS FOR ELECTROSTATICS AND VDW\n'
    lines += '; -----------------------------------------------------------------------------------------\n'
    lines += 'coulombtype              = PME                    ; [1]\n'
    lines += 'coulomb-modifier         = Potential-shift-Verlet ; ??? \n'
    lines += 'rcoulomb-switch          = 0\n'
    lines += 'rcoulomb                 = 1.2                    ; [1]\n'
    lines += 'epsilon-r                = 1                      ; relative eps. for the medium -> \n'
    lines += 'epsilon-rf               = 0                      ; [1]\n'
    lines += 'vdw-type                 = cut-off\n'
    lines += 'vdw-modifier             = Potential-shift-Verlet\n'
    lines += 'rvdw-switch              = 0\n'
    lines += 'rvdw                     = 1.2                    ; [1]\n'
    lines += 'DispCorr                 = no \n'
    lines += 'table-extension          = 1\n'
    lines += 'energygrp-table          = \n'
    lines += 'fourierspacing           = 0.12\n'
    lines += 'fourier-nx               = 0\n'
    lines += 'fourier-ny               = 0\n'
    lines += 'fourier-nz               = 0\n'
    lines += 'pme_order                = 4\n'
    lines += 'ewald_rtol               = 1e-05\n'
    lines += 'ewald_rtol_lj            = 1e-03\n'
    lines += 'lj-pme-comb-rule         = geometric\n'
    lines += 'ewald_geometry           = 3d\n'
    lines += 'epsilon_surface          = 0\n'
    lines += 'implicit-solvent         = No\n'
    lines += '\n'
    lines += '\n'
    lines += '; OPTIONS FOR WEAK COUPLING ALGORITHMS\n'
    lines += '; -----------------------------------------------------------------------------------------\n'
    lines += 'tcoupl                   = V-rescale            ; We equilibriate so this is good enough\n'
    lines += 'nsttcouple               = -1                    ; default\n'
    lines += 'nh-chain-length          = 10                   ; N/A\n'
    lines += 'print-nose-hoover-chain-variables = no          ; N/A\n'
    lines += 'tc-grps                  = system               ; For small molecules OK\n'
    lines += 'tau-t                    = 0.1                  ; default\n'
    lines += 'ref-t                    = 500                  ; standard condition\n'
    lines += ';pcoupl                   = Berendsen               \n'
    lines += ';pcoupltype               = isotropic            ; We equilibriate so this is good enough\n'
    lines += ';nstpcouple               = -1 \n'
    lines += ';tau-p                    = 1.0\n'
    lines += ';compressibility          = 4.5e-5              ; [1]\n'
    lines += ';ref-p                    = 1\n'
    lines += ';refcoord-scaling         = all                 ; Scaling of reference coordinates, No, All or COM\n'
    lines += '\n'
    lines += '\n'
    lines += '; GENERATE VELOCITIES FOR STARTUP RUN\n'
    lines += '; -----------------------------------------------------------------------------------------\n'
    lines += 'gen-vel                  = yes        ; for free energy stuff we dont want this\n'
    lines += 'gen-temp                 = 500        ; N/A\n'
    lines += 'gen-seed                 = -1         ; N/A\n'
    lines += '\n'
    lines += '; OPTIONS FOR BONDS    \n'
    lines += '; -----------------------------------------------------------------------------------------\n'
    lines += 'constraints              = None       ; [1] water is done via shake\n'
    lines += '; Type of constraint algorithm\n'
    lines += 'constraint-algorithm     = Lincs      ; default\n'
    lines += 'continuation             = no         ; default\n'
    lines += 'Shake-SOR                = no         ; default\n'
    lines += 'shake-tol                = 0.0001     ; default also same as in [1]\n'
    lines += 'lincs-order              = 4          ; default\n'
    lines += 'lincs-iter               = 1          ; default\n'
    lines += 'lincs-warnangle          = 90         ; default\n'
    lines += 'morse                    = no         ; default\n'
    lines += '\n'
    lines += '; Free energy variables\n'
    lines += ';------------------------------------------------------------------------------------------\n'
    lines += 'free-energy              = no  ; only for equilibriation\n'

    dir_target = "./02-MD_EQ01_NVT"
    if os.path.exists(dir_target):
        shutil.rmtree(dir_target)
    os.mkdir(dir_target)
    os.chdir(dir_target)
    with open("./eq1_NVT.mdp", "w") as fnpt:
        fnpt.writelines(lines)

    lines = '#!/bin/bash\n'
    lines += '#SBATCH --partition=#PARTITION#\n'
    lines += '#SBATCH -n #NPROCESORS#\n'
    lines += '#SBATCH -N 1\n'
    lines += '#SBATCH --gres=gpu:1\n'
    lines += '#SBATCH --mem-per-cpu=3G\n'
    name = os.path.splitext(os.path.split(topologyfile)[-1])[0]
    lines += '#SBATCH --job-name=#JOBNAME#\n'
    lines += '\n'
    lines += '#module purge\n'
    lines += '#module load foss GROMACS/2021.5\n'
    lines += ';source {}/GMXRC.bash\n'.format(os.path.split(gmxpath)[0])
    lines += 'source #GMXRCPATH#\n'
    lines += '\n'
    lines += '\n'
    coordinates_file = "../01-MD_MIN/confout.gro"
    lines += 'MDP="{}"\n'.format("eq1_NVT.mdp")
    lines += 'GRO="{}"\n'.format(coordinates_file)
    lines += 'TOP="{}"\n'.format(os.path.join("../00-FORCE_FIELD_POLYPLY", topologyfile))
    lines += '\n'
    lines += 'gmx grompp -f $MDP -c $GRO -p $TOP -o new_topo.tpr --maxwarn 5 >& outgro.dat\n'
    lines += 'gmx mdrun -gpu_id 0 -pin auto -nt 14 -bonded gpu -update gpu -nb gpu -pme gpu ' \
             '-s new_topo.tpr -v -noappend  >& outmd.dat\n'
    lines += '#gmx mdrun -s new_topo.tpr -v -noappend  >& outmd.dat\n'
    lines += '#echo 0|gmx trjconv -f traj_comp.part0001.xtc -o traj_unwrap.xtc -pbc whole -s new_topo.tpr'
    lines += '\n'
    lines += r'rm \#*\n'
    lines += '\n'
    lines += '\n'

    with open("./sendslurm_nvt_gpu.sh", "w") as fnpt:
        fnpt.writelines(lines)

    os.chdir("../")


# ===============================================================================================
def gmx_eq2_npt_template(gmxpath, topologyfile, md_steps=5000000, dt=0.001):

    lines = ';----------------------------------------------------------------------------------------------------\n'
    lines += '; Author      : Javier Ramos\n'
    lines += '; Last Edited : 12.02.2024\n'
    lines += ';---------------------------------------------------------------------------------------------------\n'
    lines += '\n'
    lines += '\n'
    lines += '; RUN CONTROL PARAMETERS\n'
    lines += '; --------------------------------------------------------------------------------------------------\n'
    lines += 'integrator               = md      ; for equilibriation this is good\n'
    lines += 'tinit                    = 0       ; default\n'
    lines += 'dt                       = {0:7.3f} ; [1]\n'.format(dt)
    lines += 'nsteps                   = {0:10d} ; {1:7.1f}ps NPT Sampling time\n'.format(md_steps, md_steps*dt)
    lines += 'init-step                = 0       ; default\n'
    lines += 'simulation-part          = 1       ; default\n'
    lines += 'comm-mode                = Linear  ; default\n'
    lines += 'nstcomm                  = 100     ; [1]\n'
    lines += 'comm-grps                = system  ; [1]\n'
    lines += '\n'
    lines += '; OUTPUT CONTROL OPTIONS\n'
    lines += '; --------------------------------------------------------------------------------------------------\n'
    lines += 'nstxout                  = 0\n'
    lines += 'nstvout                  = 0\n'
    lines += 'nstfout                  = 0\n'
    lines += 'nstlog                   = 10000\n'
    lines += 'nstcalcenergy            = 10000\n'
    lines += 'nstenergy                = 10000\n'
    lines += 'nstxout-compressed       = 10000\n'
    lines += 'compressed-x-precision   = 1000\n'
    lines += 'compressed-x-grps        = \n'
    lines += 'energygrps               = \n'
    lines += '\n'
    lines += '\n'
    lines += '; NEIGHBORSEARCHING PARAMETERS\n'
    lines += '; ---------------------------------------------------------------------------------------\n'
    lines += 'cutoff-scheme            = verlet  ; should be faster at same accuracy\n'
    lines += 'nstlist                  = 40      ; [1]\n'
    lines += 'ns_type                  = grid    ; default\n'
    lines += 'pbc                      = xyz     ; [1]\n'
    lines += 'periodic-molecules       = no\n'
    lines += 'verlet-buffer-tolerance  = 1e-6    ; non-default but should improve accuracy\n'
    lines += 'rlist                    = 1.1     ; default\n'
    lines += '\n'
    lines += '\n'
    lines += '; OPTIONS FOR ELECTROSTATICS AND VDW\n'
    lines += '; -----------------------------------------------------------------------------------------\n'
    lines += 'coulombtype              = PME                    ; [1]\n'
    lines += 'coulomb-modifier         = Potential-shift-Verlet ; ??? \n'
    lines += 'rcoulomb-switch          = 0\n'
    lines += 'rcoulomb                 = 1.2                    ; [1]\n'
    lines += 'epsilon-r                = 1                      ; relative eps. for the medium -> \n'
    lines += 'epsilon-rf               = 0                      ; [1]\n'
    lines += 'vdw-type                 = cut-off\n'
    lines += 'vdw-modifier             = Potential-shift-Verlet\n'
    lines += 'rvdw-switch              = 0\n'
    lines += 'rvdw                     = 1.2                    ; [1]\n'
    lines += 'DispCorr                 = no \n'
    lines += 'table-extension          = 1\n'
    lines += 'energygrp-table          = \n'
    lines += 'fourierspacing           = 0.12\n'
    lines += 'fourier-nx               = 0\n'
    lines += 'fourier-ny               = 0\n'
    lines += 'fourier-nz               = 0\n'
    lines += 'pme_order                = 4\n'
    lines += 'ewald_rtol               = 1e-05\n'
    lines += 'ewald_rtol_lj            = 1e-03\n'
    lines += 'lj-pme-comb-rule         = geometric\n'
    lines += 'ewald_geometry           = 3d\n'
    lines += 'epsilon_surface          = 0\n'
    lines += 'implicit-solvent         = No\n'
    lines += '\n'
    lines += '\n'
    lines += '; OPTIONS FOR WEAK COUPLING ALGORITHMS\n'
    lines += '; -----------------------------------------------------------------------------------------\n'
    lines += 'tcoupl                   = V-rescale            ; We equilibriate so this is good enough\n'
    lines += 'nsttcouple               = -1                    ; default\n'
    lines += 'nh-chain-length          = 10                   ; N/A\n'
    lines += 'print-nose-hoover-chain-variables = no          ; N/A\n'
    lines += 'tc-grps                  = system               ; For small molecules OK\n'
    lines += 'tau-t                    = 0.1                  ; default\n'
    lines += 'ref-t                    = 500                  ; standard condition\n'
    lines += 'pcoupl                   = Berendsen               \n'
    lines += 'pcoupltype               = isotropic            ; We equilibriate so this is good enough\n'
    lines += 'nstpcouple               = -1 \n'
    lines += 'tau-p                    = 1.0\n'
    lines += 'compressibility          = 4.5e-5              ; [1]\n'
    lines += 'ref-p                    = 1\n'
    lines += 'refcoord-scaling         = all                 ; Scaling of reference coordinates, No, All or COM\n'
    lines += '\n'
    lines += '\n'
    lines += '; GENERATE VELOCITIES FOR STARTUP RUN\n'
    lines += '; -----------------------------------------------------------------------------------------\n'
    lines += 'gen-vel                  = yes        ; for free energy stuff we dont want this\n'
    lines += 'gen-temp                 = 500        ; N/A\n'
    lines += 'gen-seed                 = -1         ; N/A\n'
    lines += '\n'
    lines += '; OPTIONS FOR BONDS    \n'
    lines += '; -----------------------------------------------------------------------------------------\n'
    lines += 'constraints              = None       ; [1] water is done via shake\n'
    lines += '; Type of constraint algorithm\n'
    lines += 'constraint-algorithm     = Lincs      ; default\n'
    lines += 'continuation             = no         ; default\n'
    lines += 'Shake-SOR                = no         ; default\n'
    lines += 'shake-tol                = 0.0001     ; default also same as in [1]\n'
    lines += 'lincs-order              = 4          ; default\n'
    lines += 'lincs-iter               = 1          ; default\n'
    lines += 'lincs-warnangle          = 90         ; default\n'
    lines += 'morse                    = no         ; default\n'
    lines += '\n'
    lines += '; Free energy variables\n'
    lines += ';------------------------------------------------------------------------------------------\n'
    lines += 'free-energy              = no  ; only for equilibriation\n'

    dir_target = "./03-MD_EQ02_NPT"
    if os.path.exists(dir_target):
        shutil.rmtree(dir_target)
    os.mkdir(dir_target)
    os.chdir(dir_target)
    with open("./eq2_NPT.mdp", "w") as fnpt:
        fnpt.writelines(lines)

    lines = '#!/bin/bash\n'
    lines += '#SBATCH --partition=#PARTITION#\n'
    lines += '#SBATCH -n #NPROCESORS#\n'
    lines += '#SBATCH -N 1\n'
    lines += '#SBATCH --gres=gpu:1\n'
    lines += '#SBATCH --mem-per-cpu=3G\n'
    name = os.path.splitext(os.path.split(topologyfile)[-1])[0]
    lines += '#SBATCH --job-name=#JOBNAME#\n'
    lines += '\n'
    lines += '#module purge\n'
    lines += '#module load foss GROMACS/2021.5\n'
    lines += ';source {}/GMXRC.bash\n'.format(os.path.split(gmxpath)[0])
    lines += 'source #GMXRCPATH#\n'
    lines += '\n'
    lines += '\n'
    lines += 'MDP="{}"\n'.format("eq2_NPT.mdp")
    lines += 'TPR="{}"\n'.format("../02-MD_EQ01_NVT/new_topo.tpr")
    lines += 'CPI="{}"\n'.format("../02-MD_EQ01_NVT/state.cpt")
    lines += 'TOP="{}"\n'.format(os.path.join("../00-FORCE_FIELD_POLYPLY", topologyfile))
    lines += '\n'
    lines += 'gmx grompp -f $MDP -p $TOP -c $TPR -t $CPI -o new_topo.tpr --maxwarn 5 >& outgro.dat\n'
    lines += 'gmx mdrun -gpu_id 0 -pin auto -nt 14 -bonded gpu -update gpu -nb gpu ' \
             '-s new_topo.tpr -v -noappend  >& outmd.dat\n'
    lines += '#gmx mdrun -s new_topo.tpr -v -noappend  >& outmd.dat\n'
    lines += '#echo 0|gmx trjconv -f traj_comp.part0001.xtc -o traj_unwrap.xtc -pbc whole -s new_topo.tpr'
    lines += '\n'
    lines += r'rm \#*\n'
    lines += '\n'
    lines += '\n'

    with open("./sendslurm_nptBerensen_gpu.sh", "w") as fnpt:
        fnpt.writelines(lines)

    os.chdir("../")


# ===============================================================================================
def gmx_prod_npt_template(gmxpath, topologyfile, md_steps=5000000, dt=0.002):

    lines = ';----------------------------------------------------------------------------------------------------\n'
    lines += '; Author      : Javier Ramos\n'
    lines += '; Last Edited : 12.02.2024\n'
    lines += ';---------------------------------------------------------------------------------------------------\n'
    lines += '\n'
    lines += '\n'
    lines += '; RUN CONTROL PARAMETERS\n'
    lines += '; --------------------------------------------------------------------------------------------------\n'
    lines += 'integrator               = md      ; for equilibriation this is good\n'
    lines += 'tinit                    = 0       ; default\n'
    lines += 'dt                       = {0:7.3f} ; [1]\n'.format(dt)
    lines += 'nsteps                   = {0:10d} ; {1:7.1f}ps NPT Sampling time\n'.format(md_steps, md_steps*dt)
    lines += 'init-step                = 0       ; default\n'
    lines += 'simulation-part          = 1       ; default\n'
    lines += 'comm-mode                = Linear  ; default\n'
    lines += 'nstcomm                  = 10000   ; [1]\n'
    lines += 'comm-grps                = system  ; [1]\n'
    lines += '\n'
    lines += '; OUTPUT CONTROL OPTIONS\n'
    lines += '; --------------------------------------------------------------------------------------------------\n'
    lines += 'nstxout                  = 0\n'
    lines += 'nstvout                  = 0\n'
    lines += 'nstfout                  = 0\n'
    lines += 'nstlog                   = 10000\n'
    lines += 'nstcalcenergy            = 10000\n'
    lines += 'nstenergy                = 10000\n'
    lines += 'nstxout-compressed       = 10000\n'
    lines += 'compressed-x-precision   = 1000\n'
    lines += 'compressed-x-grps        = \n'
    lines += 'energygrps               = \n'
    lines += '\n'
    lines += '\n'
    lines += '; NEIGHBORSEARCHING PARAMETERS\n'
    lines += '; ---------------------------------------------------------------------------------------\n'
    lines += 'cutoff-scheme            = verlet  ; should be faster at same accuracy\n'
    lines += 'nstlist                  = 40      ; [1]\n'
    lines += 'ns_type                  = grid    ; default\n'
    lines += 'pbc                      = xyz     ; [1]\n'
    lines += 'periodic-molecules       = no\n'
    lines += 'verlet-buffer-tolerance  = 1e-6    ; non-default but should improve accuracy\n'
    lines += 'rlist                    = 1.1     ; default\n'
    lines += '\n'
    lines += '\n'
    lines += '; OPTIONS FOR ELECTROSTATICS AND VDW\n'
    lines += '; -----------------------------------------------------------------------------------------\n'
    lines += 'coulombtype              = PME                    ; [1]\n'
    lines += 'coulomb-modifier         = Potential-shift-Verlet ; ??? \n'
    lines += 'rcoulomb-switch          = 0\n'
    lines += 'rcoulomb                 = 1.2                    ; [1]\n'
    lines += 'epsilon-r                = 1                      ; relative eps. for the medium -> \n'
    lines += 'epsilon-rf               = 0                      ; [1]\n'
    lines += 'vdw-type                 = cut-off\n'
    lines += 'vdw-modifier             = Potential-shift-Verlet\n'
    lines += 'rvdw-switch              = 0\n'
    lines += 'rvdw                     = 1.2                    ; [1]\n'
    lines += 'DispCorr                 = no \n'
    lines += 'table-extension          = 1\n'
    lines += 'energygrp-table          = \n'
    lines += 'fourierspacing           = 0.12\n'
    lines += 'fourier-nx               = 0\n'
    lines += 'fourier-ny               = 0\n'
    lines += 'fourier-nz               = 0\n'
    lines += 'pme_order                = 4\n'
    lines += 'ewald_rtol               = 1e-05\n'
    lines += 'ewald_rtol_lj            = 1e-03\n'
    lines += 'lj-pme-comb-rule         = geometric\n'
    lines += 'ewald_geometry           = 3d\n'
    lines += 'epsilon_surface          = 0\n'
    lines += 'implicit-solvent         = No\n'
    lines += '\n'
    lines += '\n'
    lines += '; OPTIONS FOR WEAK COUPLING ALGORITHMS\n'
    lines += '; -----------------------------------------------------------------------------------------\n'
    lines += 'tcoupl                   = V-rescale            ; We equilibriate so this is good enough\n'
    lines += 'nsttcouple               = -1                    ; default\n'
    lines += 'nh-chain-length          = 10                   ; N/A\n'
    lines += 'print-nose-hoover-chain-variables = no          ; N/A\n'
    lines += 'tc-grps                  = system               ; For small molecules OK\n'
    lines += 'tau-t                    = 0.1                  ; default\n'
    lines += 'ref-t                    = 500                  ; standard condition\n'
    lines += 'pcoupl                   = C-rescale               \n'
    lines += 'pcoupltype               = isotropic            ; We equilibriate so this is good enough\n'
    lines += 'nstpcouple               = -1 \n'
    lines += 'tau-p                    = 5.0\n'
    lines += 'compressibility          = 4.5e-5              ; [1]\n'
    lines += 'ref-p                    = 1\n'
    lines += 'refcoord-scaling         = all                 ; Scaling of reference coordinates, No, All or COM\n'
    lines += '\n'
    lines += '\n'
    lines += '; GENERATE VELOCITIES FOR STARTUP RUN\n'
    lines += '; -----------------------------------------------------------------------------------------\n'
    lines += 'gen-vel                  = yes        ; for free energy stuff we dont want this\n'
    lines += 'gen-temp                 = 500        ; N/A\n'
    lines += 'gen-seed                 = -1         ; N/A\n'
    lines += '\n'
    lines += '; OPTIONS FOR BONDS    \n'
    lines += '; -----------------------------------------------------------------------------------------\n'
    lines += 'constraints              = h-bonds    ; [1] water is done via shake\n'
    lines += '; Type of constraint algorithm\n'
    lines += 'constraint-algorithm     = Lincs      ; default\n'
    lines += 'continuation             = no         ; default\n'
    lines += 'Shake-SOR                = no         ; default\n'
    lines += 'shake-tol                = 0.0001     ; default also same as in [1]\n'
    lines += 'lincs-order              = 4          ; default\n'
    lines += 'lincs-iter               = 1          ; default\n'
    lines += 'lincs-warnangle          = 90         ; default\n'
    lines += 'morse                    = no         ; default\n'
    lines += '\n'
    lines += '; Free energy variables\n'
    lines += ';------------------------------------------------------------------------------------------\n'
    lines += 'free-energy              = no  ; only for equilibriation\n'

    dir_target = "./04-MD_NPT"
    if os.path.exists(dir_target):
        shutil.rmtree(dir_target)
    os.mkdir(dir_target)
    os.chdir(dir_target)
    with open("./NPT.mdp", "w") as fnpt:
        fnpt.writelines(lines)

    lines = '#!/bin/bash\n'
    lines += '#SBATCH --partition=#PARTITION#\n'
    lines += '#SBATCH -n #NPROCESORS#\n'
    lines += '#SBATCH -N 1\n'
    lines += '#SBATCH --gres=gpu:1\n'
    lines += '#SBATCH --mem-per-cpu=3G\n'
    name = os.path.splitext(os.path.split(topologyfile)[-1])[0]
    lines += '#SBATCH --job-name=#JOBNAME#\n'
    lines += '\n'
    lines += '#module purge\n'
    lines += '#module load foss GROMACS/2021.5\n'
    lines += ';source {}/GMXRC.bash\n'.format(os.path.split(gmxpath)[0])
    lines += 'source #GMXRCPATH#\n'
    lines += '\n'
    lines += '\n'
    lines += 'MDP="{}"\n'.format("NPT.mdp")
    lines += 'TPR="{}"\n'.format("../03-MD_EQ02_NPT/new_topo.tpr")
    lines += 'CPI="{}"\n'.format("../03-MD_EQ02_NPT/state.cpt")
    lines += 'TOP="{}"\n'.format(os.path.join("../00-FORCE_FIELD_POLYPLY", topologyfile))
    lines += '\n'
    lines += 'gmx grompp -f $MDP -p $TOP -c $TPR -t $CPI -o new_topo.tpr --maxwarn 5 >& outgro.dat\n'
    lines += 'gmx mdrun -gpu_id 0 -pin auto -nt 14 -bonded gpu -update gpu -nb gpu -pme gpu ' \
             '-s new_topo.tpr -v -noappend  >& outmd.dat\n'
    lines += '#gmx mdrun -s new_topo.tpr -v -noappend  >& outmd.dat\n'
    lines += '#echo 0|gmx trjconv -f traj_comp.part0001.xtc -o traj_unwrap.xtc -pbc whole -s new_topo.tpr'
    lines += '\n'
    lines += r'rm \#*\n'
    lines += '\n'
    lines += '\n'

    with open("./sendslurm_nptBerensen_gpu.sh", "w") as fnpt:
        fnpt.writelines(lines)

    os.chdir("../")
